services:
  - type: web
    name: wedo-taskys-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: "./dist"
    envVars:
      - key: VITE_API_URL
        value: https://wedo-taskys-backend.onrender.com  # Ajusta seg√∫n el nombre que le des
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    plan: free