services:
  - type: web
    name: wedo-taskys-backend
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false  # la defines en el dashboard o en Render Blueprint vars
      - key: JWT_SECRET
        sync: false
    plan: free

  - type: static
    name: wedo-taskys-frontend
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://wedo-taskys-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    plan: free